# Generated by Django 5.2.13 on 2026-04-16 19:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('shop', models.CharField(max_length=128, verbose_name='Цех')),
                ('normal_min', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Норма от')),
                ('normal_max', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Норма до')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(verbose_name='Время начала')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='planned', max_length=32, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обход',
                'verbose_name_plural': 'Обходы',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=32, unique=True, verbose_name='Табельный номер')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(max_length=128, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='defects/', verbose_name='Фото')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=32, verbose_name='Критичность')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='core.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Считанное значение')),
                ('instrument_photo', models.ImageField(blank=True, null=True, upload_to='readings/instruments/', verbose_name='Фото прибора')),
                ('is_out_of_norm', models.BooleanField(default=False, verbose_name='Отклонение от нормы')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.equipment', verbose_name='Оборудование')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.inspection', verbose_name='Обход')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['inspection', 'equipment'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('archived', 'Архив')], default='draft', max_length=32, verbose_name='Статус')),
                ('equipment', models.ManyToManyField(blank=True, related_name='routes', to='core.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.route', verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='core.worker', verbose_name='Сотрудник'),
        ),
    ]
